#!/usr/bin/env sh
set -eu

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
compose_file="$script_dir/../compose.yaml"
container_engine=${MEDIASTERU_CONTAINER_ENGINE:-docker}

if [ -t 0 ] && [ -t 1 ]; then
    exec "$container_engine" compose -f "$compose_file" exec mediasteru mediasteru "$@"
fi
exec "$container_engine" compose -f "$compose_file" exec -T mediasteru mediasteru "$@"
