name: Java App CI

on:
  push:
  pull_request:

jobs:
  java:
    name: Maven package
    runs-on: ubuntu-latest
    container: maven:3.9.11-eclipse-temurin-21
    steps:
      - uses: actions/checkout@v5
      - run: mvn package -DskipDistributionAssembly=true --no-transfer-progress
